### ISSUE TITLE
Fix links on GitHub README

### ISSUE THREAD

**Issue by orthagh** [flyve-mdm/flyve-mdm-web-ui#1]
They target teclib.infra.
I saw:
* mattermost
* Download the latest release.
* issue guidelines 
* please open a new issue.
*  Wiki of Taiga.
* Wiki of GitLab.

**Comment by ajsb85** [comment]
Hi @orthagh 

Already edited.
<https://github.com/flyve-mdm/flyve-mdm-web-ui/blob/master/README.md>
Can you review again?

Thanks.

**Comment by orthagh** [comment]
seems good :+1:
