### ISSUE TITLE
Demo dashboard with UI problems

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/flyve-mdm-web-ui#100]
### Description
Demo site for Flyve MDM has user interface problems in Google Crome mobile web browser.

### Expected behavior
Better UI/UX

### Actual behavior
Dashboard in blank.
Menu with missing icons.
Links problems (some icon exceute a logout).
Text overlap.
Tabs missing.
More than one modal messages.

### Environment Details

- Web UI version: demo
- GLPi version: 9.1
- Browser Type: Google Chrome
- Browser Version: 61.0.3163.98
- OS: Android Smarshmellow
- Stack Traces:
- Angular Version:
- Angular Material Version:

### Steps to reproduce the behaviour

Login & navigate throught it

### References

- http://demo.flyve.org

### Screenshots
![screenshot_20171008-074708 1](https://user-images.githubusercontent.com/1426313/32229035-3d93dfa4-be26-11e7-800c-40e92aaf07a6.png)

![screenshot_20171008-074729 1](https://user-images.githubusercontent.com/1426313/32229088-62a70b40-be26-11e7-92c5-6403a2e1dac2.png)
(the teclib logo is over the login area).

![screenshot_20171008-074821 1](https://user-images.githubusercontent.com/1426313/32229107-710edbc2-be26-11e7-9f1a-42435fae7007.png)

![screenshot_20171008-074848 1](https://user-images.githubusercontent.com/1426313/32229115-78efc2c0-be26-11e7-9999-219b6d374426.png)

![screenshot_20171008-074857 1](https://user-images.githubusercontent.com/1426313/32229132-85abfde4-be26-11e7-91a9-cef7c00e7eb3.png)

![screenshot_20171008-075019 1](https://user-images.githubusercontent.com/1426313/32229157-8f94c124-be26-11e7-90d7-4456f52a53b5.png)

![screenshot_20171008-075039 1](https://user-images.githubusercontent.com/1426313/32229169-9559ce1a-be26-11e7-8429-781dc23c2244.png)

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 

Thanks for the feedback.
This dashboard is deprecated, the new dashboard is coming and these are the issues related:

https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/6
https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/51

**Comment by DIOHz0r** [comment]
Ok. I got here by the android app. 

cc: @rafaelje
