### ISSUE TITLE
Endpoint change to split demo mode

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-web-ui#27]
### Description

The backend in on its way to move the demo mode into a dedicated plugin. This impacts some endpoints 

- PluginFlyvemdmUser becomes PluginFlyvemdmdemoUser
- PluginFlyvemdmAccountvalidation becomes PluginFlyvemdmdemoAccountvalidation

### Expected behavior

up to date endpoints

### Actual behavior

not yet updated

**Comment by ajsb85** [comment]
closed 315934b03ebe51cd994771468fa687aac7c6d9e4

**Comment by btry** [comment]
Change done, closing
