### ISSUE TITLE
Multi-language

### ISSUE THREAD

**Issue by dlarget** [flyve-mdm/flyve-mdm-web-ui#28]
### Description
Multi-language (french - english - spanish)
### Expected behavior
We have to be able to change language of web-ui

**Comment by ajsb85** [comment]
Hi @dlarget 

The translations works.

I am using Transifex + Grunt + Angular Translate.

https://angular-translate.github.io
https://github.com/angular-translate/angular-translate

I will commit my changes when all strings are ready (in english) to upload to Transifex.

Salut.

**Comment by ajsb85** [comment]
Hi, @Gianfranco97.

We need to work on this task with support i18n / l10n compatible with React and Transifex.

**Comment by Gianfranco97** [comment]
@ajsb85 Sure, I'll investigate how to do it
