### ISSUE TITLE
applciation upload broken

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-web-ui#29]
### Description

When I upload an application for Adroid, the backend answers HTTP 400 "Unabme to save the file"

### Expected behavior

upload should suceed

### Actual behavior

upload failed 

### Environment Details

- Web UI version:
- GLPi version:
- Browser Type:
- Browser Version:
- OS:
- Stack Traces:
- Angular Version:
- Angular Material Version:

### Steps to reproduce the behaviour

1. login to the frontend
2 try to upload a file

### References

example of payload when uploading a file
------WebKitFormBoundaryHLxTFCeUyjml8zgh
Content-Disposition: form-data; name="file"; filename="com.traffar.a24game_4.apk"
Content-Type: application/vnd.android.package-archive

------WebKitFormBoundaryHLxTFCeUyjml8zgh
Content-Disposition: form-data; name="uploadManifest"

{"input":{"alias":"com.traffar.a24game_4.apk"}}
------WebKitFormBoundaryHLxTFCeUyjml8zgh--

### Screenshots

$_FILES variable in the backend
![image](https://cloud.githubusercontent.com/assets/14139801/23267623/992d00a2-f9eb-11e6-90c2-ce5ddb0be1a6.png)

the name is null, and the backend expects to find a name with an extension.

**Comment by ajsb85** [comment]
@btry In the demo works in preprod (https://flyve-mdm.github.io/flyve-mdm-web-ui) does not works

**Comment by btry** [comment]
At the very beginning of the execution of the backend here is what I see
![image](https://cloud.githubusercontent.com/assets/14139801/23269658/95cf6c96-f9f1-11e6-857d-edb76e018b07.png)

Then the filename is populated, and something deletes it...

Now I think the bug does not comes from the frontend.

**Comment by btry** [comment]
The issue belongs to GLPI. $_FILES is sanitized, but for an unknown readon for now, the sanitized $_FILES is damaged. 

Method Toolbox::addslashes_deep() called in Toolbox::sanitize() seems to be buggy now.

**Comment by ajsb85** [comment]
@btry 👍🏻 close then please
