### ISSUE TITLE
Can't run flyve-mdm-web-ui

### ISSUE THREAD

**Issue by ZlobniyDaemon** [flyve-mdm/flyve-mdm-web-ui#30]
### Description
After all steps in Readme.md file were done, i run 'Grunt' command and receive the following output:
"Running "clean:server" (clean) task
» 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:test" (concurrent) task

    Running "compass:dist" (compass) task
    directory .tmp/styles
        write .tmp/styles/app.css (2.401s)

    Running "compass:server" (compass) task

    Done.

    Execution Time (2017-02-27 09:36:55 UTC+3)
    loading tasks                   1.7s  ▇▇▇▇▇▇▇ 20%
    loading grunt-contrib-compass  280ms  ▇▇ 3%
    compass:dist                    4.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 51%
    compass:server                  2.2s  ▇▇▇▇▇▇▇▇▇ 26%
    Total 8.4sDEPRECATION WARNING:
    Sass 3.5 will no longer support Ruby 1.9.3.
    Please upgrade to Ruby 2.0.0 or greater as soon as possible.

    DEPRECATION WARNING:
    Sass 3.5 will no longer support Ruby 1.9.3.
    Please upgrade to Ruby 2.0.0 or greater as soon as possible.

Running "autoprefixer:server" (autoprefixer) task
» 1 autoprefixed stylesheet created.

Running "autoprefixer:dist" (autoprefixer) task
» 1 autoprefixed stylesheet created.

Running "connect:test" (connect) task
Started connect web server on http://localhost:9001

Running "karma:unit" (karma) task
27 02 2017 09:37:08.762:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:8000/
27 02 2017 09:37:08.765:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
27 02 2017 09:37:08.771:INFO [launcher]: Starting browser PhantomJS
27 02 2017 09:37:10.326:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket fFALxTG8ihf1qO84AAAA with id 8173
PhantomJS 2.1.1 (Linux 0.0.0): Executed 3 of 3 SUCCESS (0.059 secs / 0.206 secs)

=============================== Coverage summary ===============================
Statements   : 6.73% ( 167/2482 )
Branches     : 3.19% ( 16/501 )
Functions    : 3.24% ( 26/802 )
Lines        : 6.8% ( 167/2455 )
================================================================================

Done.

Execution Time (2017-02-27 09:36:47 UTC+3)
loading tasks                5.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 22%
wiredep:app                 724ms  ▇▇▇▇ 3%
loading grunt-concurrent    516ms  ▇▇▇ 2%
concurrent:test              9.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 40%
loading grunt-autoprefixer   1.1s  ▇▇▇▇▇ 5%
autoprefixer:server         460ms  ▇▇ 2%
karma:unit                   5.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 23%
Total 23.7s"

After it nothing happens.
### Expected behavior
running Аднму-mdm-web-ui
### Actual behavior
nothing happens.
### Environment Details
- Web UI version: 2.0.0
- GLPi version: 9.2
- Browser Type: Firefox
- Browser Version: 51.0.1
- OS: Windows 7 Pro x64

### Steps to reproduce the behaviour

1. Follow the instructions in Readme.md
1. Run 'Grunt test' command

**Comment by ajsb85** [comment]
Hi @ZlobniyDaemon

The proper command is `grunt serve`

**Comment by ZlobniyDaemon** [comment]
@ajsb85 
When I run the grunt serve command, the execution hangs on
```
Running "watch" task
Waiting...
```

**Comment by ajsb85** [comment]
@ZlobniyDaemon Hi
This command should open the web browser with the URL http://localhost:9001

**Comment by ajsb85** [comment]
Hi @ZlobniyDaemon 

You can download the demo file in the release information to run the app.
You need to configure the config.js to your proper information.

https://github.com/flyve-mdm/flyve-mdm-web-ui/releases

![image](https://cloud.githubusercontent.com/assets/663460/23788712/172bbe5c-0578-11e7-850b-b853c398969c.png)
