### ISSUE TITLE
Enter password screen - 5" Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#65]
![5 phone portrait](https://user-images.githubusercontent.com/663460/27844121-6da69ecc-611d-11e7-9fcb-7d775df63b6b.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-login-1499448231280 1](https://user-images.githubusercontent.com/19965590/27969177-e4165a10-6317-11e7-8b25-3a29700bac21.png)

**Comment by ajsb85** [comment]
Add the new logo for the Web Admin Dashboard.

The sources of the logo here:
https://github.com/flyve-mdm/flyve-mdm-press-kit/tree/develop/logotype

![artboard 2](https://user-images.githubusercontent.com/663460/28137877-19ce53ac-674f-11e7-9007-f3000e27244b.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-login 1](https://user-images.githubusercontent.com/19965590/28140985-a04a26a8-6728-11e7-86ac-031cbd45b123.png)
