### ISSUE TITLE
Sign in screen - 5" Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#66]
![artboard 3](https://user-images.githubusercontent.com/663460/27854596-bd0e940c-6167-11e7-9c9e-ee632f2e2dfb.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-login-1499370306256](https://user-images.githubusercontent.com/19965590/27931381-1228d9d8-6268-11e7-8521-dab6df2979bf.png)

**Comment by ajsb85** [comment]
The link "What's this?" is a dialog with promotional information about Flyve MDM

![imagen](https://user-images.githubusercontent.com/663460/27962686-f3d72a90-6332-11e7-8bcb-340b9de25109.png)

You can copy the text from here:

http://www.teclib-edition.com/en/teclib-products/flyve-mobile-device-management/

**Comment by Gianfranco97** [comment]
Mmm ... I do not en liking me, but that's the element that gives me React-Win
![captura de pantalla 2017-07-07 a la s 2 25 23 p m](https://user-images.githubusercontent.com/19965590/27971323-49e9039e-6320-11e7-97d8-7477ed7d8d87.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Use the same theme color of this spec
https://flyve-mdm.github.io/flyve-mdm-press-kit/bootstrap/

**Comment by Gianfranco97** [comment]
Here is an example with all components of React-Win http://winjs.github.io/react-winjs/examples/showcase/index.html

**Comment by ajsb85** [comment]
New logotype

![artboard 3](https://user-images.githubusercontent.com/663460/28144450-d23c89ec-676b-11e7-96da-661a26965e5e.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-](https://user-images.githubusercontent.com/19965590/28167360-637c8294-67a9-11e7-875c-7f03bbcf7ea7.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-login 3](https://user-images.githubusercontent.com/19965590/28280831-0e11f8be-6af3-11e7-92b0-27d0eaec2c31.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Remember to use these guidelines: https://flyve-mdm.github.io/flyve-mdm-press-kit/bootstrap/typography.html

**Comment by Gianfranco97** [comment]
![localhost-3000-validateuser 4](https://user-images.githubusercontent.com/19965590/28339987-1c6ab9ca-6bdc-11e7-979e-8e4877d9bb44.png)
