### ISSUE TITLE
Resend activation email screen - 5" Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#67]
* When the user try to login without activation.
* When the user cannot find the email of validation he can see what is the email and resent the activation link

![artboard 4](https://user-images.githubusercontent.com/663460/27854676-00313d84-6168-11e7-874e-efd0de80637c.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-validateuser 1](https://user-images.githubusercontent.com/19965590/28082811-868242ec-6641-11e7-8786-1fe2fd638a4e.png)

**Comment by btry** [comment]
If you show here the lifetime of the activation link, I think I shall provide a way to get this duration. Who know, maybe we will change it someday.

**Comment by Gianfranco97** [comment]
As I understand.
1.When registering, I am sent an activation link (apart from opening this screen that allows me to request that I be sent again)
2.After entering the email and clicking the link pertinete would open this screen: https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/68
3.Then click on the valid and ready button
4.In case the link is expired this screen will appear: https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/71
5.And in case the account is already active, the screen will appear: https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/69

The truth is that I do not know how this process will be carried out in the backend

**Comment by Gianfranco97** [comment]
In fact, it would be very helpful what pass me the endpoints with which I have to communicate to do this

**Comment by ajsb85** [comment]
New logotype

![artboard 4](https://user-images.githubusercontent.com/663460/28144432-bdcfbd80-676b-11e7-8316-a1dc6e0b976b.png)

**Comment by ajsb85** [comment]
Improves for this screen

* Change your email action.
* Visit the help center

![imagen](https://user-images.githubusercontent.com/663460/28314961-ea129dd6-6bbc-11e7-939e-ace1f0c83485.png)

**Comment by ajsb85** [comment]
* Edit email address

![imagen](https://user-images.githubusercontent.com/663460/28315042-2fcb3f18-6bbd-11e7-9380-a13989d5416f.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-resendvalidationuser](https://user-images.githubusercontent.com/19965590/28319545-2aa4e320-6b9c-11e7-8ff4-55cb587625e1.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-resendvalidationuser 1](https://user-images.githubusercontent.com/19965590/28319951-47dd2e38-6b9d-11e7-8d45-f065edc8f8a2.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-editemailaddress](https://user-images.githubusercontent.com/19965590/28325605-3f22ea08-6bac-11e7-838b-cc4a7547a97e.png)
