### ISSUE TITLE
 Validate account link screen - 5" Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#68]
* When the user open the link, he can see the email associated with the account.
* The email is use for the login screen later.

![artboard 5](https://user-images.githubusercontent.com/663460/27854899-d12e5e12-6168-11e7-9a86-a427866ac3dd.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-validateuser-1499373416908](https://user-images.githubusercontent.com/19965590/27931756-5cabbf56-6269-11e7-93e0-eb969ef6acab.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-validateuser-1499373472105](https://user-images.githubusercontent.com/19965590/27931801-7d7c63b6-6269-11e7-8121-8baf75377372.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 5](https://user-images.githubusercontent.com/663460/28144422-aa629e5c-676b-11e7-966e-d66783c1e610.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-validateuser 2](https://user-images.githubusercontent.com/19965590/28167253-f95b1a06-67a8-11e7-8c8e-725c795d6d23.png)
