### ISSUE TITLE
Validated account link screen - 5" Phone Portrait 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#69]
* When the user open the link and the account is already activated the user can see the email associated with the account.
* The email is used to the login screen.
* The validation button is disabled.

![artboard 6](https://user-images.githubusercontent.com/663460/27854997-1b9389a0-6169-11e7-8574-ba9ca0f35e4e.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-validateuser](https://user-images.githubusercontent.com/19965590/28035628-5566e5b4-6583-11e7-8f10-8aa73db9217e.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 6](https://user-images.githubusercontent.com/663460/28144404-94dc3f48-676b-11e7-9a5e-32f658051dc2.png)
