### ISSUE TITLE
 Sign in after validation success screen - 5" Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#70]
* This screen appear after the validation success.
* The email is taken from the validation link in the before screen.

![artboard 7](https://user-images.githubusercontent.com/663460/27855158-af529ec4-6169-11e7-9c8f-e4b3a13b6f44.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-login-1499699561411](https://user-images.githubusercontent.com/19965590/28025185-b9a85904-6560-11e7-99e6-73cc181381ae.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-login-1499699765593](https://user-images.githubusercontent.com/19965590/28025368-34b9e630-6561-11e7-9b62-42690a4df5a1.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 7](https://user-images.githubusercontent.com/663460/28144396-8cfa5044-676b-11e7-979c-a1a297008d01.png)
