### ISSUE TITLE
 Validation link expired screen - 5" Phone Portrait 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#71]
* Expired error message.
* The email is used for the next sign up screen.

![artboard 8](https://user-images.githubusercontent.com/663460/27855533-16a94aea-616b-11e7-8404-3ceda3216347.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 8](https://user-images.githubusercontent.com/663460/28144381-75615252-676b-11e7-9e9d-1e7608326305.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-validateuser 9](https://user-images.githubusercontent.com/19965590/28371736-c7b0a486-6c6b-11e7-9a9a-18282077aac7.png)

**Comment by ajsb85** [comment]
@Gianfranco97 It's a error message, why not red?

**Comment by Gianfranco97** [comment]
I was copying the image you sent me. I change it already

**Comment by Gianfranco97** [comment]
![localhost-3000-validateuser 10](https://user-images.githubusercontent.com/19965590/28372034-a89d9daa-6c6c-11e7-9f26-77d699770649.png)

**Comment by Gianfranco97** [comment]
so?

**Comment by ajsb85** [comment]
@Gianfranco97 You are right, good change.

**Comment by Gianfranco97** [comment]
good
