### ISSUE TITLE
Revoke invitation link screen - 5" Phone Portrait 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#72]
* Someone might have just mistyped their email address and accidentally tried to add yours.

![artboard 9](https://user-images.githubusercontent.com/663460/27855605-620e6150-616b-11e7-9b5b-8c343e9b9734.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-revokeinvitation-1499462330496](https://user-images.githubusercontent.com/19965590/27977358-5dc380e8-6338-11e7-9fad-a75e385b6a2e.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 9](https://user-images.githubusercontent.com/663460/28144368-6851080a-676b-11e7-9d5a-f86292e7bac7.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-revokeinvitation 1](https://user-images.githubusercontent.com/19965590/28167192-be009cec-67a8-11e7-9ff7-4a9f87203d1a.png)
