### ISSUE TITLE
Revoke invitation sucess  screen - 5" Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#73]
* Opt-out / unsuscribed - sucess screen

![artboard 10](https://user-images.githubusercontent.com/663460/27855698-be28352e-616b-11e7-9ed1-d6ee1c4fe00a.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-revokeinvitation](https://user-images.githubusercontent.com/19965590/28030927-9f9fb738-6573-11e7-910a-84cd12b27e37.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 10](https://user-images.githubusercontent.com/663460/28144469-f0faecc0-676b-11e7-808d-83654fd6c635.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-revokeinvitation 2](https://user-images.githubusercontent.com/19965590/28179163-15c07fc6-67cf-11e7-899b-533785b93b5c.png)
