### ISSUE TITLE
 Password recovery screen - 5" Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#74]
![artboard 11](https://user-images.githubusercontent.com/663460/27855982-c74bd7e0-616c-11e7-85a7-d747cdb72bcd.png)

**Comment by Gianfranco97** [comment]
Not it is necessary a button of submit?

**Comment by ajsb85** [comment]
@Gianfranco97 Yes, "Cancel" and "Next"

**Comment by Gianfranco97** [comment]
Fine

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-recoveraccount-1499456667014](https://user-images.githubusercontent.com/19965590/27974303-6bb84e98-632b-11e7-957c-47e02cca04e3.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Could you show how looks the validation of the field for the email and for the characters of the captcha?

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-recoveraccount-1499459988077](https://user-images.githubusercontent.com/19965590/27976071-f2f1778e-6332-11e7-829e-0624ed8b43b6.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Don't have the same margin and alignment of before validations.

**Comment by ajsb85** [comment]
Posible error messages

* Email requered
* Invalid email
* Captcha requiered
* Characters do not match image. Try again.

**Comment by Gianfranco97** [comment]
The mistakes I have are:

- Required field
- Invalid email
- Characters do not match image. Try again.

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-recoveraccount-1499461169958](https://user-images.githubusercontent.com/19965590/27976702-ae71a69e-6335-11e7-87c3-fe11f5699a03.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Great!

**Comment by ajsb85** [comment]
New logotype

![artboard 11](https://user-images.githubusercontent.com/663460/28144348-505cf5ec-676b-11e7-9323-03ec7b163979.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-recoveraccount](https://user-images.githubusercontent.com/19965590/28285943-88b5b720-6b04-11e7-8c48-140f4bfe1767.png)
