### ISSUE TITLE
Create account screen - 5" Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#76]
![artboard 13](https://user-images.githubusercontent.com/663460/27865594-7db273ec-6193-11e7-824d-d87edb8f06c6.png)

**Comment by Gianfranco97** [comment]
Please you could pass the specifications of the typography used? @ajsb85

**Comment by Gianfranco97** [comment]
### Any suggestions for captcha?

**Comment by ajsb85** [comment]
@Gianfranco97 Bypass the captcha for now

**Comment by Gianfranco97** [comment]
Ok

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-createaccount-1499435575901](https://user-images.githubusercontent.com/19965590/27960665-21b23fce-62fa-11e7-98e3-a9ade617c2ce.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-createaccount-1499437120954](https://user-images.githubusercontent.com/19965590/27961765-dd512e5e-62fd-11e7-9097-5df033c08d8c.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-createaccount-1499437510870](https://user-images.githubusercontent.com/19965590/27962013-968f4310-62fe-11e7-94a7-46ccddbd9429.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Remove "Not" and add margin after "Sign In" link

**Comment by Gianfranco97** [comment]
### Done
![screencapture-localhost-3000-createaccount-1499437715694](https://user-images.githubusercontent.com/19965590/27962178-10b14918-62ff-11e7-84d5-65ad3201ffb2.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Good job.
Could you show the error messages in the fields and the toggle in on?

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-createaccount-1499437715694](https://user-images.githubusercontent.com/19965590/27962388-c4a7426a-62ff-11e7-8642-8035be682ea0.png)

**Comment by Gianfranco97** [comment]
![screencapture-localhost-3000-createaccount-1499438056230](https://user-images.githubusercontent.com/19965590/27962416-d95fb9ee-62ff-11e7-9d59-c83f01649bec.png)

**Comment by Gianfranco97** [comment]
Missing captcha errors, I'll add them when it's working

**Comment by ajsb85** [comment]
@Gianfranco97 Main color Blue for the Toggle?

**Comment by Gianfranco97** [comment]
It's the one that comes with the theme, let me see how I can change it

**Comment by Gianfranco97** [comment]
### ready
![screencapture-localhost-3000-createaccount-1499438650807](https://user-images.githubusercontent.com/19965590/27962905-49acb106-6301-11e7-8b87-689f9932b099.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 13](https://user-images.githubusercontent.com/663460/28144314-151cf8f6-676b-11e7-8a28-fff7b3193640.png)

**Comment by Gianfranco97** [comment]
### Done
![captura de pantalla 2017-07-17 a la s 12 26 07 p m](https://user-images.githubusercontent.com/19965590/28278461-38568f3e-6aeb-11e7-9c23-ded63bf491e5.png)
