### ISSUE TITLE
HTML 5 Push History

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#77]
- Bypassing Jekyll on GitHub Pages
   https://github.com/blog/572-bypassing-jekyll-on-github-pages
- Redirect with 404 to the index.html
   https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by Gianfranco97** [comment]
I am not using Jekyll to publish the page, so far I have been using gh-page https://github.com/tschaub/gh-pages

**Comment by ajsb85** [comment]
@Gianfranco97 Yes. The bypass is to disable Jekyll

**Comment by Gianfranco97** [comment]
# Deploy error
```
ts-loader: Using typescript@2.3.4 and /Users/mac3/Documents/GitHub/flyve-mdm-web-ui/tsconfig.json
Skipping static resource "/Users/mac3/Documents/GitHub/flyve-mdm-web-ui/build/static/js/main.c678e1b7.js" (5.43 MB) - max size is 2.1 MB
Failed to compile.

static/js/main.c678e1b7.js from UglifyJs
Invalid assignment [./~/source-map-loader!./src/Utils/GetCredentials.js:27,20][static/js/main.c678e1b7.js:87432,87]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

**Comment by Gianfranco97** [comment]
https://github.com/facebookincubator/create-react-app/issues/2612

**Comment by Gianfranco97** [comment]
I am changing the code of the '.js' files from ES6 to ES5

**Comment by Gianfranco97** [comment]
https://github.com/facebookincubator/create-react-app/issues/2433

**Comment by Gianfranco97** [comment]
## New error message during deploy
```console
ts-loader: Using typescript@2.3.4 and /Users/mac3/Documents/GitHub/flyve-mdm-web-ui/tsconfig.json
Skipping static resource "/Users/mac3/Documents/GitHub/flyve-mdm-web-ui/build/static/js/main.3e9f2b8a.js" (5.43 MB) - max size is 2.1 MB
Failed to compile.

static/js/main.3e9f2b8a.js from UglifyJs
Unexpected token: punc (,) [static/js/main.3e9f2b8a.js:87501,10]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

**Comment by Gianfranco97** [comment]
![captura de pantalla 2017-07-17 a la s 9 53 34 a m](https://user-images.githubusercontent.com/19965590/28271210-f0555bee-6ad5-11e7-9bf2-8288752af99d.png)

**Comment by Gianfranco97** [comment]
![captura de pantalla 2017-07-17 a la s 10 47 44 a m](https://user-images.githubusercontent.com/19965590/28273894-776153f2-6add-11e7-911e-69b70c88856a.png)

![captura de pantalla 2017-07-17 a la s 10 47 24 a m](https://user-images.githubusercontent.com/19965590/28273909-7fb6acd2-6add-11e7-9024-93a3b9e19bff.png)

![captura de pantalla 2017-07-17 a la s 10 47 12 a m](https://user-images.githubusercontent.com/19965590/28273920-873d83ae-6add-11e7-9427-5cf6f713265b.png)
