### ISSUE TITLE
Create 404 on github

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-web-ui#78]
### Description
Create 404 on github

**Comment by ajsb85** [comment]
@Gianfranco97 Duplicated https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/77

**Comment by Gianfranco97** [comment]
Thank you

**Comment by ajsb85** [comment]
@Gianfranco97 Add the label "duplicated" and close this issue
