### ISSUE TITLE
Register an account screencast

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#79]
Hi, @Gianfranco97 

This is a list of issues to fix in the workflow:

- [x] * Remove the blank screen in the second 30: https://youtu.be/weMFGKqIoSw?t=30s
- [x] * Disable button after click/tap in "Create Account"
- [x] * Disable button "Resend invitation" for 3 seconds of every click/tap.
- [x] * Maybe a full screen with alpha/transparency for the spinner (circular progress loader) is better to show. 
- [x] * Add the animation to enter to the "Verify your identity" https://msdn.microsoft.com/en-us/library/windows/apps/hh701582.aspx
- [x] * Grammar issue in the "Identify" change to "Identity".
- [x] * Remove the password after every fail of the validation.
- [x] * Validate password after user leave password field. (Using blur)

[![Create account success](http://img.youtube.com/vi/weMFGKqIoSw/0.jpg)](https://youtu.be/weMFGKqIoSw)

**Comment by Gianfranco97** [comment]
- ### Remove the blank screen in the second 30

What happens here is that the component to verify their identity has an asynchronous load, to present a personalized content depending on who requests it. That is why there is a charge before rederizarce

**Comment by Gianfranco97** [comment]
-  ### Disable button "Resend invitation" for 3 seconds of every click/tap.

3 seconds or 30 seconds?

**Comment by ajsb85** [comment]
@Gianfranco97 3 seconds, this is a feture to prevent multiples request or flood...

**Comment by ajsb85** [comment]
@Gianfranco97 Try to hide the rendering with the spinner. And show the content after the rendered is completed

**Comment by Gianfranco97** [comment]
- ### Maybe a full screen with alpha/transparency for the spinner (circular progress loader) is better to show.

something like this?

![captura de pantalla 2017-07-12 a la s 9 05 23 a m](https://user-images.githubusercontent.com/19965590/28119116-b15bdb4a-66e1-11e7-9321-17ba4da5785a.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Yes. The same funcionality of the other spinners.

**Comment by Gianfranco97** [comment]
- ### Try to hide the render process. And show after the rendered is completed

@ajsb85 I have a spinners not to display a completely blank screen, but I have to wait for the api to give me an answer. And if I want to be able to maintain that independent component I have to make that petition within the same component

**Comment by Gianfranco97** [comment]
- ### Disable button after click/tap in "Create Account"
Done

**Comment by Gianfranco97** [comment]
- ### Grammar issue in the "Identify" change to "Identity".
Done

![captura de pantalla 2017-07-12 a la s 10 36 01 a m](https://user-images.githubusercontent.com/19965590/28123064-0005af6c-66ee-11e7-9268-ea5f6ca4cb3a.png)

**Comment by Gianfranco97** [comment]
- ### Maybe a full screen with alpha/transparency for the spinner (circular progress loader) is better to show.

Done

**Comment by Gianfranco97** [comment]
- ### Add the animation to enter to the "Verify your identity" https://msdn.microsoft.com/en-us/library/windows/apps/hh701582.aspx

As I assumed, this was not going to work easily

So it was the only way of implementing it occurred to me that it might work:

![captura de pantalla 2017-07-12 a la s 2 01 51 p m](https://user-images.githubusercontent.com/19965590/28132662-791eb8d6-670b-11e7-9e86-7ceaa26a110c.png)

But I end up being a failure, there is no animation, it is as if it will never be executed

**Comment by Gianfranco97** [comment]
It turns out that if it works like I did, but the effect is very subtle and it does not look like the example video of the documentation

**Comment by Gianfranco97** [comment]
The effect it does is the same as WinJS.UI.Animation.enterPage https://msdn.microsoft.com/en-us/library/windows/apps/br212672.aspx

**Comment by ajsb85** [comment]
@Gianfranco97 More animations and examples: https://code.msdn.microsoft.com/windowsapps/Using-the-Animation-787f3720/sourcecode?fileId=50840&pathId=1401128080

**Comment by Gianfranco97** [comment]
- ### Add the animation to enter to the "Verify your identity"
Done
