### ISSUE TITLE
Revoke an invitation screencast

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#80]
Hi, @Gianfranco97 

This is a list of issues to fix in the workflow:

* Disable button after click/tap in "Opt-out"

[![Create account success](http://img.youtube.com/vi/88lHWwjaIwo/0.jpg)](https://youtu.be/88lHWwjaIwo)

**Comment by Gianfranco97** [comment]
- ### Disable button after click/tap in "Opt-out"
Done
