### ISSUE TITLE
Validate account screencast

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#81]
Hi, @Gianfranco97 

This is a list of issues to fix in the workflow:

- [x] * Disable button after click/tap in "Validate".
- [x] * Add the full screen spinner (circular progress loader) with alpha/transparency between the "Verify your identity" and "Sign In".
- [x] * Add the animation to enter to the "Sign In" and "Enter password" screens, here example of the enter content animation:  https://msdn.microsoft.com/en-us/library/windows/apps/hh701582.aspx
- [x] * Grammar issue in the "Identify" change to "Identity".
- [x] * Wait to finish the full load of the "Users" page to remove the spinner.
- [x] * After click/tap in "Close session" show the "Sign In" screen with the proper animation (spinner and enter content animation).

[![Validate Account](http://img.youtube.com/vi/Fyd5fqjRUcg/0.jpg)](https://youtu.be/Fyd5fqjRUcg)

**Comment by Gianfranco97** [comment]
- ### Wait to finish the full load of the "Users" page to remove the spinner.

This is already done

- the first, load is the validation of the user


![captura de pantalla 2017-07-12 a la s 9 16 08 a m](https://user-images.githubusercontent.com/19965590/28119695-c261f7ec-66e3-11e7-89bb-000cf775131b.png)

- the second, verifies that the user is verified 


![captura de pantalla 2017-07-12 a la s 9 17 09 a m](https://user-images.githubusercontent.com/19965590/28119704-caf52b68-66e3-11e7-91c4-4a38da6d2035.png)

- the third, that makes request and loading the array of users for the list


![captura de pantalla 2017-07-12 a la s 9 18 06 a m](https://user-images.githubusercontent.com/19965590/28119712-d36e8136-66e3-11e7-9807-816d9eda591d.png)

**Comment by Gianfranco97** [comment]
- ### Add the full screen spinner (circular progress loader) with alpha/transparency between the "Verify your identity" and "Sign In".
Done

**Comment by Gianfranco97** [comment]
- ### Disable button after click/tap in "Validate".
Done

**Comment by Gianfranco97** [comment]
- ### Grammar issue in the "Identify" change to "Identity".
Done

![captura de pantalla 2017-07-12 a la s 10 36 01 a m](https://user-images.githubusercontent.com/19965590/28123064-0005af6c-66ee-11e7-9268-ea5f6ca4cb3a.png)
