### ISSUE TITLE
Recover account screencast

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#82]
Hi, @Gianfranco97 

This is a list of issues to fix in the workflow:

- [x] * Disable button after click/tap in "Next" and if errors messages are present.
- [x] * Show "Check your mail inbox" screen after click/tap in "Next".
- [x] * Add the animation to enter to the "Sign In" screen, here example of the enter content animation: https://msdn.microsoft.com/en-us/library/windows/apps/hh701582.aspx

[![Recover Account](http://img.youtube.com/vi/ohmb4hlEQrI/0.jpg)](https://youtu.be/ohmb4hlEQrI)

**Comment by Gianfranco97** [comment]
- ### Show "Check your mail inbox" screen after click/tap in "Next".
Done

**Comment by Gianfranco97** [comment]
- ### Add the animation to enter to the "Sign In" screen, here example of the enter content animation
I understood that you did not want the animation when you enter the page

**Comment by ajsb85** [comment]
When you enter to the page no, when you change the content yes.
