### ISSUE TITLE
Change password screen - 5" Phone Portrait feature 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#83]
This screen appear after open the link to reset the password.

Look into this PR to know possible error messages:
https://github.com/glpi-project/glpi/pull/2430/files

![artboard 15](https://user-images.githubusercontent.com/663460/28137297-0c97a03c-674d-11e7-850d-59c92e2c0869.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 15](https://user-images.githubusercontent.com/663460/28144302-04bbdcc0-676b-11e7-8dbf-8d6e9e5bb5ee.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-recoveraccountpasswordpage 1](https://user-images.githubusercontent.com/19965590/28167989-97b1a54c-67ab-11e7-8b40-9a813253bee4.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-recoveraccountpasswordpage 2](https://user-images.githubusercontent.com/19965590/28294020-5a7d79c6-6b25-11e7-883b-b73a5a5c76bc.png)
