### ISSUE TITLE
Password recovery success screen - 5" Phone Portrait 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#84]
![artboard 14](https://user-images.githubusercontent.com/663460/28137611-370c7e36-674e-11e7-81c3-3de7c1097652.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 14](https://user-images.githubusercontent.com/663460/28144284-ee0d03dc-676a-11e7-8437-a227ce3d6eaa.png)

**Comment by Gianfranco97** [comment]
![localhost-3000-recoveraccountsuccess](https://user-images.githubusercontent.com/19965590/28168692-df931c54-67ad-11e7-970b-84639a351e85.png)
