### ISSUE TITLE
Move dev version of the Web Admin Dashboard

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#89]
Hi, @Gianfranco97 

Please move the `gh-page` branch to the branch `master` of the repo flyve-mdm.github.io 
And add the CNAME to point http://flyve.org

And please make a mirror of the Help Center.

`git clone --bare git@github.com:flyve-mdm/flyve-mdm.github.io.git`

Thank you.

**Comment by Gianfranco97** [comment]
Done
